name: WeLore
authors: ['Bryan_lzh']
main: br.kt.welore.Main
depend: [BrAPI]
softdepend: [PlayerPoints,Vault,PlaceholderAPI]
version: 1.0-SNAPSHOT

commands:
  WeLore:
    aliases: [wl]
    description: 主命令
    usage: |
      /<command> see >> 查看手持物品属性
          /<command> seeme >> 查看自身属性